### ISSUE TITLE
Add support for Google shared drives/Onedrive plugin

### ISSUE THREAD

**Issue by rvishakhs** [Total-Noob-69/X-tra-Telegram#4]
Please add support for shared drives in gdrive plugin..In here almost friends are using google shared drives and onedrive for unlimited cloud storage.so could you please add shared drive support or create microsoft onedrive  upload plugin ?

**Comment by rsoorajs** [comment]
@rvishakhs #yeah very useful feature

**Comment by SnapDragon7410** [comment]
Ok i done it

**Comment by rsoorajs** [comment]
@SnapDragon7410 so it support team drives now ?

**Comment by SnapDragon7410** [comment]
@rsoorajs Yes
